import { logos } from './logos'

export const whiteLogoSources = ['github', 'medium', 'unsplash']

export const availableSources = [
  {
    source: 'afdian',
    icon: '/assets/sources/logo_afdian.png',
    description: '爱发电 - sponsor, donation',
    warning: '',
    badge: {
      label: '爱发电',
      labelColor: '946ce6',
      logo: '',
      suffix: '发电人次 / 月',
      color: '282c34',
      link: (k: string) => `https://afdian.net/@${k}`,
    },
  },
  {
    source: 'bilibili',
    icon: '/assets/sources/logo_bilibili.png',
    description: '哔哩哔哩 - 视频',
    warning: '',
    badge: {
      label: '哔哩哔哩',
      labelColor: 'FE7398',
      logo: logos.bilibili,
      suffix: '关注',
      color: '282c34',
      link: (k: string) => `https://space.bilibili.com/${k}`,
    },
  },
  {
    source: 'coolapk',
    icon: '/assets/sources/logo_coolapk.png',
    description: '酷安 - APP, Android、安卓',
    warning: '',
    badge: {
      label: '酷安',
      labelColor: '11ab60',
      logo: logos.coolapk,
      suffix: '关注',
      color: '282c34',
      link: (k: string) => `https://www.coolapk.com/u/${k}`,
    },
  },
  {
    source: 'feedly',
    icon: '/assets/sources/logo_feedly.png',
    description: 'Feedly - RSS',
    warning: '',
    badge: {
      label: 'Feedly',
      labelColor: '2bb24c',
      logo: 'feedly',
      logoColor: 'ffffff',
      suffix: 'subs',
      color: '282c34',
      link: (k: string) => k,
    },
  },
  {
    source: 'feedspub',
    icon: '/assets/sources/logo_feedspub.png',
    description: 'Feedspub - RSS',
    warning: '',
    badge: {
      label: 'Feeds Pub',
      labelColor: '282c34',
      logo: logos.feedsPub,
      suffix: 'subs',
      color: '61b04b',
      link: (k: string) => k,
    },
  },
  {
    source: 'github',
    icon: '/assets/sources/logo_github.png',
    description: 'GitHub - developer',
    warning: '',
    badge: {
      label: 'GitHub',
      labelColor: '282c34',
      logo: 'github',
      suffix: 'follows',
      color: '181717',
      link: (k: string) => `https://github.com/${k}`,
    },
  },
  {
    source: 'inoreader',
    icon: '/assets/sources/logo_inoreader.png',
    description: 'Inoreader - RSS',
    warning: 'This route is very fragile - may not always work.',
    badge: {
      label: 'Inoreader',
      labelColor: '007bc7',
      logo: logos.inoreader,
      suffix: 'subs',
      color: '282c34',
      link: (k: string) => k,
    },
  },
  {
    source: 'instagram',
    icon: '/assets/sources/logo_ins.png',
    description: 'Instagram - social',
    warning: '',
    badge: {
      label: 'Instagram',
      labelColor: 'd7417b',
      logo: 'instagram',
      logoColor: 'ffffff',
      suffix: 'follows',
      color: '282c34',
      link: (k: string) => `https://instagram.com/${k}`,
    },
  },
  {
    source: 'jike',
    icon: '/assets/sources/logo_jike.png',
    description: 'Jike - social、即刻',
    warning: '',
    badge: {
      label: '即刻',
      labelColor: '282c34',
      logo: logos.jike,
      suffix: '关注',
      color: 'fbae00',
      link: (k: string) => `https://m.okjike.com/users/${k}`,
    },
  },
  {
    source: 'medium',
    icon: '/assets/sources/logo_medium.png',
    description: 'Medium - social、文章',
    warning: '',
    badge: {
      label: 'Medium',
      labelColor: '03a87c',
      logo: 'medium',
      suffix: 'follows',
      color: '12100e',
      link: (k: string) => `https://medium.com/@${k}`,
    },
  },
  {
    source: 'neteasemusic',
    icon: '/assets/sources/logo_neteasemusic.png',
    description: '网易云音乐 - social, music',
    warning: '',
    badge: {
      label: '网易云音乐',
      labelColor: 'e72d2c',
      logo: logos.neteaseMusic,
      suffix: '粉丝',
      color: '282c34',
      link: (k: string) => `https://music.163.com/#/user/home?id=${k}`,
    },
  },
  {
    source: 'reddit',
    icon: '/assets/sources/logo_reddit.png',
    description: 'Reddit - social',
    warning: '',
    badge: {
      label: 'Reddit Karma',
      labelColor: 'ff4500',
      logo: 'reddit',
      logoColor: 'ffffff',
      suffix: '',
      color: '282c34',
      link: (k: string) => `https://www.reddit.com/user/${k}`,
    },
  },
  {
    source: 'sspai',
    icon: '/assets/sources/logo_sspai.png',
    description: '少数派 - articles、文章',
    warning: '',
    badge: {
      label: '少数派',
      labelColor: '282c34',
      logo: logos.sspai,
      suffix: '关注',
      color: 'd71a1b',
      link: (k: string) => `https://sspai.com/u/${k}`,
    },
  },
  {
    source: 'steamgames',
    icon: '/assets/sources/logo_steam.png',
    description: 'Steam (Games number) - game、游戏',
    warning: '',
    badge: {
      label: 'Steam',
      labelColor: '134375',
      logo: 'steam',
      suffix: 'games',
      color: '0b1a37',
      link: (k: string) => `https://steamcommunity.com/profiles/${k}`,
    },
  },
  {
    source: 'steamfriends',
    icon: '/assets/sources/logo_steam.png',
    description: 'Steam (Friends number) - game、游戏',
    warning: '',
    badge: {
      label: 'Steam',
      labelColor: '134375',
      logo: 'steam',
      suffix: 'friends',
      color: '0b1a37',
      link: (k: string) => `https://steamcommunity.com/profiles/${k}`,
    },
  },
  {
    source: 'telegram',
    icon: '/assets/sources/logo_tg.png',
    description: 'Telegram Channel - social、电报、频道',
    warning: '',
    badge: {
      label: 'Telegram',
      labelColor: '282c34',
      logo: 'telegram',
      suffix: 'members',
      color: '2CA5E0',
      link: (k: string) => `https://t.me/${k}`,
    },
  },
  {
    source: 'twitter',
    icon: '/assets/sources/logo_twitter.png',
    description: 'Twitter - social、推特、蓝鸟',
    warning: '',
    badge: {
      label: 'Twitter',
      labelColor: '282c34',
      logo: 'twitter',
      suffix: 'follows',
      color: '1da1f2',
      link: (k: string) => `https://twitter.com/${k}`,
    },
  },
  {
    source: 'unsplash',
    icon: '/assets/sources/logo_unsplash.png',
    description: 'Unsplash - photography, design, social',
    warning: '',
    badge: {
      label: 'Unsplash',
      labelColor: '000000',
      logo: 'unsplash',
      suffix: 'follows',
      color: '282c34',
      link: (k: string) => `https://unsplash.com/@${k}`,
    },
  },
  {
    source: 'weibo',
    icon: '/assets/sources/logo_weibo.png',
    description: '微博 - social',
    warning: '',
    badge: {
      label: '微博',
      labelColor: 'e71f19',
      logo: 'sina-weibo',
      suffix: '关注',
      color: '040000',
      link: (k: string) => `https://weibo.com/${k}`,
    },
  },
  {
    source: 'wikipediazh',
    icon: '/assets/sources/logo_wikipedia.png',
    description: 'Wikipedia 中文 - 维基百科',
    warning: '',
    badge: {
      label: '维基百科',
      labelColor: '000000',
      logo: 'wikipedia',
      suffix: '编辑',
      color: '282c34',
      link: (k: string) => `https://zh.wikipedia.org/wiki/User:${k}`,
    },
  },
  {
    source: 'zhihu',
    icon: '/assets/sources/logo_zhihu.png',
    description: '知乎 - social',
    warning: '',
    badge: {
      label: '知乎',
      labelColor: '0084ff',
      logo: 'zhihu',
      logoColor: 'ffffff',
      suffix: '关注',
      color: '282c34',
      link: (k: string) => `https://www.zhihu.com/people/${k}`,
    },
  },
]
