export const availableSources = [
  {
    source: 'afdian',
    icon: '/assets/sources/logo_afdian.png',
    description: '爱发电 - sponsor, donation',
    warning: '',
  },
  {
    source: 'bilibili',
    icon: '/assets/sources/logo_bilibili.png',
    description: '哔哩哔哩 - 视频',
    warning: '',
  },
  {
    source: 'coolapk',
    icon: '/assets/sources/logo_coolapk.png',
    description: '酷安 - APP, Android、安卓',
    warning: '',
  },
  { source: 'feedly', icon: '/assets/sources/logo_feedly.png', description: 'Feedly - RSS', warning: '' },
  { source: 'feedspub', icon: '/assets/sources/logo_feedspub.png', description: 'Feedspub - RSS', warning: '' },
  { source: 'github', icon: '/assets/sources/logo_github.png', description: 'GitHub - developer', warning: '' },
  {
    source: 'inoreader',
    icon: '/assets/sources/logo_inoreader.png',
    description: 'Inoreader - RSS',
    warning: 'This route is very fragile - may not always work.',
  },
  {
    source: 'instagram',
    icon: '/assets/sources/logo_ins.png',
    description: 'Instagram - social',
    warning: '',
  },
  { source: 'jike', icon: '/assets/sources/logo_jike.png', description: 'Jike - social、即刻', warning: '' },
  {
    source: 'medium',
    icon: '/assets/sources/logo_medium.png',
    description: 'Medium - social、文章',
    warning: '',
  },
  {
    source: 'neteasemusic',
    icon: '/assets/sources/logo_neteasemusic.png',
    description: '网易云音乐 - social, music',
    warning: '',
  },
  { source: 'reddit', icon: '/assets/sources/logo_reddit.png', description: 'Reddit - social', warning: '' },
  {
    source: 'sspai',
    icon: '/assets/sources/logo_sspai.png',
    description: '少数派 - articles、文章',
    warning: '',
  },
  {
    source: 'steamgames',
    icon: '/assets/sources/logo_steam.png',
    description: 'Steam (Games number) - game、游戏',
    warning: '',
  },
  {
    source: 'steamfriends',
    icon: '/assets/sources/logo_steam.png',
    description: 'Steam (Friends number) - game、游戏',
    warning: '',
  },
  {
    source: 'telegram',
    icon: '/assets/sources/logo_tg.png',
    description: 'Telegram Channel - social、电报、频道',
    warning: '',
  },
  {
    source: 'twitter',
    icon: '/assets/sources/logo_twitter.png',
    description: 'Twitter - social、推特、蓝鸟',
    warning: '',
  },
  {
    source: 'unsplash',
    icon: '/assets/sources/logo_unsplash.png',

    description: 'Unsplash - photography, design, social',
    warning: '',
  },
  { source: 'weibo', icon: '/assets/sources/logo_weibo.png', description: '微博 - social', warning: '' },
  {
    source: 'wikipediazh',
    icon: '/assets/sources/logo_wikipedia.png',
    description: 'Wikipedia 中文 - 维基百科',
    warning: '',
  },
  { source: 'zhihu', icon: '/assets/sources/logo_zhihu.png', description: '知乎 - social', warning: '' },
]
