name: Deploy to production

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: worker

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers (Production)
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build
        run: pnpm build

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "production"
          workingDirectory: "worker"
